USE shopdb;
DESCRIBE customers;
SELECT * FROM customers;

-- wht is the total revenue generated by male vs female customers?
select gender,sum(purchase_amount) as revenue
from customers
group by gender;

-- which customer used a discount but stoll spent more than the average purchase amount
select customer_id, purchase_amount
from customers
where discount_applied = 'Yes' and purchase_amount >=(select avg(purchase_amount) from customers);

-- which are the top 5 products with the hightest average review rating
SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS Average_rating
FROM customers
GROUP BY item_purchased
ORDER BY Average_rating DESC
LIMIT 5;

-- compare the average purchase amount between standard and express shipping
select shipping_type ,avg(purchase_amount)
from customers
where shipping_type in ('Standard','Express')
group by shipping_type;

-- do subscribe customers spend more? compare avrega spend and total revenue
-- between subscribton and non subscribers
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2)as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customers
group by subscription_status
order by total_revenue,avg_spend desc;

-- which 5 products have the highest percentage of purchases with discount applied
SELECT 
    item_purchased,
    ROUND(
        SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) 
        * 100.0 / COUNT(*),
        2
    ) AS discount_rate
FROM customers
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- segement customers into new, returning and loyal based on their total
-- number of previous purchases, and show the count of each segement
with customer_type as (
select customer_id,previous_purchases,
case
    when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segement
from customers
)
select customer_segement,count(*) as 'Number_of_customers'
from customer_type
group by customer_segement;

-- what are the 3 most purchased products within each category
with item_counts as (
select category, item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id)DESC)as item_rank
from customers
group by category,item_purchased)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <=3;

-- are customers who are repeat buyers(more then 5 previous purchases)also likely to subscribe
select subscription_status,
count(customer_id) as repeat_buyers
from customers
where previous_purchases >5
group by subscription_status;

-- what is the revenue contribution of each age group
select age,
sum(purchase_amount) as total_revenue
from customers
group by age
order by total_revenue desc;
